#+  summary: Test
#+  endpoint: https://sparql.goldenagents.org/sparql
#+  pagination: 20

PREFIX hg: <http://rdf.histograph.io/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  GRAPH <https://data.goldenagents.org/datasets/ufab7d657a250e3461361c982ce9b38f3816e0c4b/saa_index_op_kwijtscheldingen_enriched_20191205> {
  	?document <https://data.goldenagents.org/datasets/SAA/ontology/mentionsProperty> ?property .
    
    ?property rdfs:label ?wktLabel, ?wktTooltip; 
              hg:liesIn ?area .
    
    ?area a hg:Area ;
          geo:hasGeometry/geo:asWKT ?wkt .
  }
} LIMIT 100