#+ summary: Adresses Golden Agents with streetnames starting with 'zee'
#+ description: Example query for testing the HuC Geo Plugin for Yasgui
#+ pagination: 100
#+ endpoint: https://data.create.humanities.uva.nl/sparql

PREFIX hg: <http://rdf.histograph.io/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX schema: <https://schema.org/>
PREFIX roar: <https://w3id.org/roar#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
   ?address a roar:LocationObservation ;
       rdfs:label ?wktTooltip ;
       hg:liesIn ?street .
  
   ?street a hg:Street ;
       rdfs:label ?streetLabel ;
       geo:hasGeometry/geo:asWKT ?streetWKT .
  
   ?point a geo:Geometry ;
       schema:geoWithin ?address ;
       geo:asWKT ?wkt .
  
  FILTER(REGEX(?streetLabel, 'zee', 'i'))
  
} 
